export const ACTION_TYPE = {
    UPLOAD_PRODUCT: "UPLOAD_PRODUCT",
    REMOVE_UPLOAD_NOTIFICATION: "REMOVE_UPLOAD_NOTIFICATION",
    FETCH_ALL_PRODUCTS: "FETCH_ALL_PRODUCTS",
    FETCH_SELECTED_PRODUCT: "FETCH_SELECTED_PRODUCT",
    UDPATE_PRODUCT: "UDPATE_PRODUCT",
    RESET_UPDATE_INFO: "RESET_UPDATE_INFO",
    DELETE_SELECTED_PRODUCT: "DELETE_SELECTED_PRODUCT",
    SHOW_SIDEBAR_COMPONENT: "SHOW_SIDEBAR_COMPONENT",
    SIGN_IN_USER: "SIGN_IN_USER",
    ADD_TO_CARD: "ADD_TO_CARD",
    GET_ALL_CART_PRODUCTS: "GET_ALL_CART_PRODUCTS",
};
